// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerEconomyServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerEconomyServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<int> GetPlayerCoins()
        {
            return await k_Service.CallModuleEndpointAsync<int>(
                "TestRoomCloud",
                "GetPlayerCoins",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<TestRoomCloud.RewardRunResult> RewardRun(int runScore, bool usedContinue, string runId, int clientSaveVersion)
        {
            return await k_Service.CallModuleEndpointAsync<TestRoomCloud.RewardRunResult>(
                "TestRoomCloud",
                "RewardRun",
                new Dictionary<string, object>()
                {
                    {"runScore", runScore},
                    {"usedContinue", usedContinue},
                    {"runId", runId},
                    {"clientSaveVersion", clientSaveVersion},
                });
        }
    }
}
