// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.TestRoomCloud
{
    public partial class RewardRunResult
    {
        public int CoinsGranted;
        public int CurrentCoinBalance;
        public int BestScore;
        public bool IsNewBestScore;
        public bool RunAlreadyProcessed;

        [Preserve]
        public RewardRunResult ()
        {
        }
    }
}